In [15]:
import numpy as np
x = np.array([1, 2])
x

array([1, 2])

In [16]:
np.expand_dims(x,axis=0).T

array([[1],
       [2]])

In [14]:
np.expand_dims(x,axis=1)

array([[1],
       [2]])

In [5]:
x.dot(x)

5

In [8]:
from scipy import linalg
x = np.matrix([[1, 2], [3, 4]])
linalg.inv(x)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [9]:
x.T

matrix([[1, 3],
        [2, 4]])